# Generated by Django 4.2 on 2023-05-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
        migrations.RemoveField(
            model_name='place',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude',
        ),
        migrations.AddField(
            model_name='place',
            name='npa',
            field=models.IntegerField(default='0001'),
        ),
    ]
