# Generated by Django 4.2 on 2023-05-14 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_place_country_remove_place_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_place',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_place',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
