# Generated by Django 4.2 on 2023-05-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message_created_place_message_updated_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_place',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='updated_place',
            new_name='updated_date',
        ),
    ]
