# Generated by Django 4.2 on 2023-05-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.place'),
        ),
    ]
