# Generated by Django 4.2 on 2023-05-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_commentary_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={},
        ),
        migrations.RenameField(
            model_name='commentary',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='parent',
        ),
    ]
