# Generated by Django 4.2 on 2023-05-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_commentary_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_date',
        ),
    ]
