# Generated by Django 4.2 on 2023-05-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_commentary_options_and_more'),
        ('api', '0011_remove_message_created_date_and_more'),
    ]

    operations = [
    ]
