# Generated by Django 4.2 on 2023-05-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_commentary_placecommentary_place_createddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='places', to='api.event'),
        ),
    ]
