# Generated by Django 4.2 on 2023-05-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_place_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='events',
        ),
    ]
